name: elixir_dialyze_ockam_ockam_vault_software
on:
  workflow_dispatch:
  push:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'build.gradle'
      - 'implementations/elixir/build.gradle'
      - 'settings.gradle'
      - 'implementations/elixir/settings.gradle'
      - 'implementations/elixir/ockam/ockam_vault_software/**'

jobs:
  elixir_dialyze_ockam_ockam_vault_software:
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/ockam-network/ockam/builder@sha256:3d41b8e711888f2525b786f7751016eca0770f65c3f925909e2c1db45c8c0714
    steps:
      - name: Checkout
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4

      - id: elixir_dialyze_ockam_ockam_vault_software
        working-directory: implementations/elixir
        run: ../../gradlew dialyze_ockam_ockam_vault_software
